### PR TITLE
Use proper time units

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by wojtekmach** [comment]
Oops, we can't do that without requiring Elixir 1.4+, currently we require 1.3+. I'm gonna close it because it may not be good enough reason to bump the version but I'm happy to make the change in any case, let me know!

**Comment by whatyouhide** [comment]
@wojtekmach if you are up for it (it's boring), I'd definitely appreciate choosing the unit conditionally at compile time based on Elixir version and then unquoting it where needed :)

**Comment by wojtekmach** [comment]
@whatyouhide Done. Do you want me to set travis to test on 1.3 too? Right now it doesn't so I didn't touch tests :)

**Comment by whatyouhide** [comment]
Oh yeah that would be great, thanks @wojtekmach! 💟

**Comment by wojtekmach** [comment]
@whatyouhide turns out Jason requires 1.4 so maybe we should require it here after all?

**Comment by whatyouhide** [comment]
Thanks @wojtekmach! 💟

**Comment by whatyouhide** [comment]
Yes, please open another PR for requiring 1.4 if you want, otherwise I'll do it :)

**Comment by adamkittelson** [comment]
Hi there, just checking if there's any ETA on when a version with this code will be pushed to hex.pm? I've got a warning about the :seconds -> :second thing bubbling up to my app from rollbax that would be neat to take care of. Thanks! 😄

**Comment by whatyouhide** [comment]
Just released v0.10.0 :).

**Pull request merged**
